In [18]:
from auth_class import *
from query import *
import requests
from urllib.parse import urlencode
import random
import pandas as pd
import sys
db_df = pd.read_csv("1. Songs Analyzed.csv")
db_df = pd.DataFrame(db_df)
randomSongs = []

db_df

,id,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence
0,2SAqBLGA283SUiwJ3xOUVI,0.761,0.518,0.000000,0.147850,1.0,0.1340,0.244000,0.000035,0.107,0.522
1,0qJeyYAgv6UpvewUxRXAhb,0.874,0.443,0.416667,0.160467,0.0,0.2410,0.147000,0.000000,0.124,0.298
2,3GZd1aDsgKL71Kt3VIp0hc,0.614,0.553,0.583333,0.137083,1.0,0.1690,0.030600,0.000000,0.203,0.161
3,6nDSLDomNqfet6w0r1GHAz,0.881,0.517,0.333333,0.148600,1.0,0.3080,0.011500,0.000000,0.151,0.786
4,0PvFJmanyNQMseIFrU708S,0.823,0.586,0.500000,0.110100,0.0,0.2000,0.114000,0.000000,0.193,0.347
...,...,...,...,...,...,...,...,...,...,...,...
426,6M33HiUHLC3R3gfXYNGMAy,0.955,0.768,0.083333,0.092333,0.0,0.1810,0.013400,0.000000,0.308,0.741
427,57QFOU3f7O0gDLadxv5z8w,0.851,0.598,0.000000,0.139267,1.0,0.4390,0.000595,0.000000,0.343,0.654
428,2OqYarizUUGzSSNHPrDEii,0.700,0.518,0.333333,0.119850,0.0,0.1770,0.047100,0.000000,0.100,0.542
429,6YTp4sUEi3oWNToQvOjke6,0.880,0.693,0.083333,0.086683,1.0,0.3320,0.059900,0.000000,0.248,0.767
430,6PBAPjshd2JfEiWpdf3C2a,0.794,0.777,0.083333,0.061600,0.0,0.0813,0.098200,0.000000,0.202,0.706

In [19]:
for x in range(0, 3):
    i = random.randint(0, 430)

    while i in randomSongs:
        i = random.randint(0, 430)

    randomSongs.append(i)

randomSongID = []
for x in range (0, len(randomSongs)):
    randomSongID.append(db_df.iloc[randomSongs[x]]['id'])

randomSongID

['4iuO0dinw5Bm18pXbZok8w', '1IIKrJVP1C9N7iPtG6eOsK', '3T3SeUjR8NhTzSE3NSDxkK']

In [20]:
db_df = db_df.drop([db_df.index[randomSongs[0]], db_df.index[randomSongs[1]], db_df.index[randomSongs[2]]])
db_df = db_df.reset_index(drop=True)

In [21]:
db_df

,id,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence
0,2SAqBLGA283SUiwJ3xOUVI,0.761,0.518,0.000000,0.147850,1.0,0.1340,0.244000,0.000035,0.107,0.522
1,0qJeyYAgv6UpvewUxRXAhb,0.874,0.443,0.416667,0.160467,0.0,0.2410,0.147000,0.000000,0.124,0.298
2,3GZd1aDsgKL71Kt3VIp0hc,0.614,0.553,0.583333,0.137083,1.0,0.1690,0.030600,0.000000,0.203,0.161
3,6nDSLDomNqfet6w0r1GHAz,0.881,0.517,0.333333,0.148600,1.0,0.3080,0.011500,0.000000,0.151,0.786
4,0PvFJmanyNQMseIFrU708S,0.823,0.586,0.500000,0.110100,0.0,0.2000,0.114000,0.000000,0.193,0.347
...,...,...,...,...,...,...,...,...,...,...,...
423,6M33HiUHLC3R3gfXYNGMAy,0.955,0.768,0.083333,0.092333,0.0,0.1810,0.013400,0.000000,0.308,0.741
424,57QFOU3f7O0gDLadxv5z8w,0.851,0.598,0.000000,0.139267,1.0,0.4390,0.000595,0.000000,0.343,0.654
425,2OqYarizUUGzSSNHPrDEii,0.700,0.518,0.333333,0.119850,0.0,0.1770,0.047100,0.000000,0.100,0.542
426,6YTp4sUEi3oWNToQvOjke6,0.880,0.693,0.083333,0.086683,1.0,0.3320,0.059900,0.000000,0.248,0.767
427,6PBAPjshd2JfEiWpdf3C2a,0.794,0.777,0.083333,0.061600,0.0,0.0813,0.098200,0.000000,0.202,0.706

In [42]:
def getTrack(id):
    track = requests.get("https://api.spotify.com/v1/tracks/" + str(id), headers=spotify.get_resource_header()).json()
    artist = track['artists'][0]['name']
    songName = track['name']
    print("Now playing", songName, "by", artist)
    

ratings = []
for x in range (0, len(randomSongID)):
    getTrack(randomSongID[x])
    response = int(input("Please rate this song out of 5"))
    ratings.append(response)

Now playing Bassline by Mantronix
Please rate this song out of 54
Now playing Go Crazy by Chris Brown
Please rate this song out of 55
Now playing Move Like a Boss (feat. Young M.A) by Fivio Foreign
Please rate this song out of 52

In [43]:
ratings

[4, 5, 2]

In [54]:
randomSongID

['4iuO0dinw5Bm18pXbZok8w', '1IIKrJVP1C9N7iPtG6eOsK', '3T3SeUjR8NhTzSE3NSDxkK']

In [55]:
endpoint = 'https://api.spotify.com/v1/audio-features/'
track_id = randomSongID
i = 0
songNum = 0
colNames = []
stars = ratings

In [56]:
for song in track_id:
    r = requests.get(endpoint + song, headers=auth_header)

    names = []
    rate = stars[songNum]
    data = []

    for keys in r.json():
        if keys == "type":
            break

        elif keys == "type" or keys == "duration_ms" or keys == "tempo":
            continue

        if keys == "key":
            names.append(keys)
            val = abs(float(r.json()[keys])) / 12
            data.append(val)


        elif keys == "loudness":
            names.append(keys)
            val = abs(float(r.json()[keys])) / 60
            data.append(val)

        else:
            names.append(keys)
            data.append(float(r.json()[keys]))

    if i == 0:
        #creating the data frame for the first time

        track1 = pd.DataFrame([[data[0], data[1], data[2], data[3], data[4],
                            data[5], data[6], data[7], data[8], data[9]]], columns=names)

        df = pd.DataFrame([[data[0] * rate, data[1] * rate, data[2] * rate, data[3] * rate, data[4] * rate,
                            data[5] * rate, data[6] * rate, data[7] * rate, data[8] * rate, data[9] * rate]], columns=names)
        i = i +1
        colNames = names
    else:

        track2 = pd.DataFrame([[data[0], data[1], data[2], data[3], data[4],
                                data[5], data[6], data[7], data[8], data[9]]], columns=names)

        df2 = pd.DataFrame([[data[0] * rate, data[1] * rate, data[2] * rate, data[3] * rate, data[4] * rate,
                            data[5] * rate, data[6] * rate, data[7] * rate, data[8] * rate, data[9] * rate]], columns=names)

        df = df.append(df2, ignore_index=True)

    songNum += 1

In [57]:
df

,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence
0,3.260,3.416,3.666667,0.577600,0.0,0.824,0.072,0.0314,1.268,1.048
1,3.775,2.890,0.000000,0.744333,0.0,0.725,1.580,0.0000,1.250,2.905
2,1.596,1.586,0.166667,0.130867,2.0,0.640,0.133,0.0000,0.594,0.988

In [58]:
user_profile = df.sum(axis=0)
user_profile = pd.DataFrame(user_profile, columns=['Value Totals'])
user_profile['Weighted_Values'] = 0
user_profile

                  Value Totals  Weighted_Values
danceability          8.631000                0
energy                7.892000                0
key                   3.833333                0
loudness              1.452800                0
mode                  2.000000                0
speechiness           2.189000                0
acousticness          1.785000                0
instrumentalness      0.031400                0
liveness              3.112000                0
valence               4.941000                0

In [59]:
user_profile_totals = user_profile['Value Totals'].sum()

rowNum = 0
NEW_COL = 1
OLD_COL = 0

# creating a new column with the weighted values for each feature based on user profile
for index, row in user_profile.iterrows():
    user_profile.iloc[rowNum, NEW_COL] = user_profile.iloc[rowNum, OLD_COL] / user_profile_totals
    rowNum += 1

user_profile

                  Value Totals  Weighted_Values
danceability          8.631000         0.240635
energy                7.892000         0.220032
key                   3.833333         0.106875
loudness              1.452800         0.040505
mode                  2.000000         0.055761
speechiness           2.189000         0.061030
acousticness          1.785000         0.049766
instrumentalness      0.031400         0.000875
liveness              3.112000         0.086764
valence               4.941000         0.137757

In [61]:
preferred_vals = user_profile['Weighted_Values'].to_list()
preferred_vals

[0.24063544932929135,
 0.22003185796625735,
 0.10687474094492141,
 0.040504597472551786,
 0.05576073440604596,
 0.061030123807417305,
 0.049766455457396025,
 0.0008754435301749215,
 0.08676370273580751,
 0.13775689435013655]

In [64]:
db_df.iloc[0].to_list()

['2SAqBLGA283SUiwJ3xOUVI',
 0.7609999999999999,
 0.518,
 0.0,
 0.14785,
 1.0,
 0.134,
 0.244,
 3.47e-05,
 0.107,
 0.522]

In [76]:
def analyze(preferred_vals, db):
    
    bestSong = {}
    bestSong['id'] = "None"
    bestSong['chance'] = 0
    
    counter = 0
    for index, row in db.iterrows():
        currSong_vals = db_df.iloc[counter].to_list()
        song_id = currSong_vals.pop(0)
        
        prediction_vals = []
        for x in range(0, len(preferred_vals)):
            prediction_vals.append(preferred_vals[x] * currSong_vals[x])
            
        curr_chance = sum(prediction_vals)
        if curr_chance > bestSong['chance']:
            bestSong['id'] = song_id
            bestSong['chance'] = curr_chance
            
        
        counter += 1
        
    
    return bestSong

In [77]:
result = analyze(preferred_vals, db_df)
result

{'id': '3MN82VctKXwosPol8bzyDM', 'chance': 0.7059431874942306}

In [78]:
getTrack(result['id'])

Now playing Ladies First by Queen Latifah